### ISSUE TITLE
Missing String tools

### ISSUE THREAD

**Issue by stephanedemotte** [adrian2x/atomic-fns#9]
Hello your lib look very strong ! Great job !

Juste an idea, adding string tool like slugify, kebebCase etc could make this lib stronger :)

Thank !

**Comment by adrian2x** [comment]
Thank you @stephanedemotte! 
I think it's a great idea and definitely will look into adding those.
Do let me know if you have any other suggestions in the future.

**Comment by adrian2x** [comment]
Implemented [here](https://atomic-stack.github.io/atomic-fns/modules/string.html).
